name: Marksmith
options:
  bundleIdPrefix: com.jonathancheung
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  swift-markdown:
    url: https://github.com/swiftlang/swift-markdown.git
    from: "0.4.0"

targets:
  Marksmith:
    type: application
    platform: macOS
    sources:
      - path: Marksmith
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jonathancheung.Marksmith
        INFOPLIST_FILE: Marksmith/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Marksmith/Marksmith.entitlements
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "2"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: swift-markdown
        product: Markdown
    entitlements:
      path: Marksmith/Marksmith.entitlements

  MarksmithTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: MarksmithTests
    dependencies:
      - target: Marksmith
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Marksmith.app/Contents/MacOS/Marksmith"
        GENERATE_INFOPLIST_FILE: true
